redis_resque:  localhost:6379
redis_pyres:   localhost:6380
queue_resque:  submission_results
queue_pyres:   submissions
worker_resque: SubmissionResultHandler
worker_pyres:  worker.SubmissionChecker
web_resque:    8080
web_pyres:     8081
