require 'yaml'
require 'resque'
RESQUE_CONFIG = YAML.load_file('configs/resque.yml')

namespace :pyres do

  desc "Start 1 pyres worker."
  task :start do
    queue = RESQUE_CONFIG['queue_pyres']
    command = "PYTHONPATH=$TOC_TESTER_PATH nohup pyres_worker -f $HOME/logs/pyres_worker.log #{ queue } > /dev/null &"
    `sh -c '#{ command }' `
  end

  desc "Stops all pyres workers."
  task :stop do
    queue = RESQUE_CONFIG['queue_pyres']
    workers = Resque.workers.find_all { |w| w.queues.include?(queue) }
    puts "Killing workers: #{ workers }"

    pids = workers.map { |w| w.id.split(':')[1] }

    puts "kill -s QUIT #{pids.join(' ')}" unless pids.empty?
    `kill -s QUIT #{pids.join(' ')}` unless pids.empty?
  end
end
