require 'yaml'
require 'resque'
RESQUE_CONFIG = YAML.load_file('configs/resque.yml')

namespace :pyres do

  desc "Start 1 pyres worker."
  task :start do
    queue = RESQUE_CONFIG['queue_pyres']
    command = "PYTHONPATH=../ nohup pyres_worker -f $HOME/logs/pyres_worker.log #{ queue } > /dev/null &"
    `sh -c '#{ command }' `
  end

  desc "Stops all pyres workers."
  task :stop do
    workers = Resque.workers
    puts "Killing workers: #{ workers }"
    pids = workers.map(&:pid)

    `kill -s QUIT #{pids.join(' ')}` unless pids.empty?
  end
end
